version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: '<your_mysql_password>'  # Consider using a strong password in production
      MYSQL_DATABASE: url_shortener
    ports:
      - "3307:3306"
    volumes:
      - ./url_shortener_db.sql:/docker-entrypoint-initdb.d/url_shortener_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flask-app:
    build: .
    container_name: url-shortener-container
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=<your_mysql_password>
      - MYSQL_DATABASE=url_shortener