apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS url_shortener;
    USE url_shortener;
    CREATE TABLE IF NOT EXISTS redirections (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      long_url VARCHAR(1024) NOT NULL,
      short_url VARCHAR(20) UNIQUE DEFAULT NULL
    ); 